#!/bin/sh

# Background + colors
sh ~/.fehbg
. "${HOME}/.config/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color0"

bspc monitor -d 1 2 3 4 5 6 # 7 8 9 0

bspc config border_width            2
bspc config window_gap              8
bspc config single_monocle          true
bspc config split_ratio             0.50
bspc config focus_follows_pointer   false
bspc config swallow_first_click     false
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side

#Floating applications
bspc rule -a polybar private

#Open applications on specific workspaces
# bspc rule -a firefox desktop='^1'
# bspc rule -a steam desktop='4'
# bspc rule -a "Spotify" desktop='^6'

$HOME/.config/bspwm/autostart.sh

